version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app_prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://twitteruser:twitterpassword@mysql_prod:3306/twitter_production
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: twitter_production
      MYSQL_USER: twitteruser
      MYSQL_PASSWORD: twitterpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3308:3306'
    networks:
      - backend

networks:
  backend:
    driver: bridge
